sudo: required
services:
  - docker

before_install:
  - docker build -t ktatarhuk/udemy-docker-kube-fib-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ktatarhuk/udemy-docker-kube-fib-react-test npm test

after_sucess:
  - docker build -t ktatarhuk/udemy-docker-kube-fib-client ./client
  - docker build -t ktatarhuk/udemy-docker-kube-fib-nginx ./nginx
  - docker build -t ktatarhuk/udemy-docker-kube-fib-server ./server
  - docker build -t ktatarhuk/udemy-docker-kube-fib-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Push images to docker hub
  - docker push ktatarhuk/udemy-docker-kube-fib-client
  - docker push ktatarhuk/udemy-docker-kube-fib-nginx
  - docker push ktatarhuk/udemy-docker-kube-fib-server 
  - docker push ktatarhuk/udemy-docker-kube-fib-worker 